Clinical trials
oncokb/oncokb pull request #2485
Opened 2021-03-09 15:31 UTC by Leowisd

This implements https://github.com/oncokb/oncokb/issues/2479

2021-03-23 19:44 UTC, zhx828 requested changes
the .json.gz should not be included in the repo.

2021-03-23 19:44 UTC, zhx828 commented on web/src/main/java/org/mskcc/cbio/oncokb/api/pub/v1/TrialsApiController.java
> +        value = "/trials/cancerType",
The api path does not make sense to me. I would rather use `trials-by-cancer-type`

2021-03-23 19:44 UTC, zhx828 commented on web/src/main/java/org/mskcc/cbio/oncokb/api/pub/v1/TrialsApiController.java
> +            value = "Consisted of single/multuple drugs. Support drugs name or drugs' NCIT code. For multiple drugs treatment, use '+' as separator. Example: Everolimus+C95701"
```suggestion
            value = "Consisted of single/multiple drugs. Support drug name or NCIT code. For multiple drugs treatment, use '+' as separator. Example: Binimetinib+Ribociclib"
```

2021-03-23 19:44 UTC, zhx828 commented on web/src/main/java/org/mskcc/cbio/oncokb/api/pub/v1/TrialsApiController.java
> +            value = "The radius from your location. Must be specified with address and country. Example: 100, which means all trails have any site locates within 100 km from your location. If not spe
These descriptions should be put into constant and share with annotation endpoints.

2021-03-25 02:21 UTC, Leowisd commented on core/src/main/java/org/mskcc/cbio/oncokb/util/ClinicalTrialsUtils.java
> +            .map(id -> getAllTrials().get(id))
I think each trial should have nctId from the pipeline

2021-03-25 02:37 UTC, Leowisd commented on core/src/main/java/org/mskcc/cbio/oncokb/util/CacheUtils.java
> +    };
It makes sense. Remove the observer of the clinical trials.

2021-03-25 23:39 UTC, Leowisd commented on core/src/main/java/org/mskcc/cbio/oncokb/util/ClinicalTrialsUtils.java
> +        os.close();
https://stackoverflow.com/questions/14503881/strange-behavior-when-deserializing-nested-generic-classes-with-gson/14506181#14506181

2021-03-26 02:18 UTC, Leowisd commented on core/src/main/java/org/mskcc/cbio/oncokb/util/GzipUtils.java
> +public class GzipUtils {
Don't find specific library util to use.

2021-04-05 18:15 UTC, zhx828 requested changes
We need to prefill the coordinates for all sites in the sites.json For anyone without/or cannot find coordinates, we need to give some defaults(maybe -1,-1, or do not search the location if the coordinates null) to let the script knows it has been searched. Otherwise, every time you make a search, the script looks for locations for the ones without the coordinates.

2021-04-05 18:16 UTC, zhx828 commented
@Leowisd could you give me a list of distinct recruitmentStatus? I'm wondering whether we should filter out the sites without recruiting.

2021-04-05 18:22 UTC, zhx828 commented
@Leowisd could you also check why sites of NCT02799095 do not include any locations outside of united states? It's a match  when I search toronto/canada/MEL

2021-04-05 18:25 UTC, zhx828 commented
@Leowisd also in the sites.json, the recruitment_status/recruitment_status_date will be different trial from trial. The sites.json should not include this info.

2021-04-06 14:29 UTC, Leowisd commented
> @Leowisd could you give me a list of distinct recruitmentStatus? I'm wondering whether we should filter out the sites without recruiting.

2021-04-06 14:30 UTC, Leowisd commented
> @Leowisd could you also check why sites of NCT02799095 do not include any locations outside of united states? It's a match when I search toronto/canada/MEL

ACTIVE
INACTIVE 
APPROVED  
COMPLETED 
ADMINISTRATIVELY_COMPLETE 
CLOSED_TO_ACCRUAL 
TEMPORARILY_CLOSED_TO_ACCRUAL 
CLOSED_TO_ACCRUAL_AND_INTERVENTION 
WITHDRAWN

2021-04-09 13:02 UTC, zhx828 requested changes

2021-04-09 13:02 UTC, zhx828 commented on core/src/test/java/org/mskcc/cbio/oncokb/util/ClinicalTrialsUtilsTest.java
> +                "C:\\Users\\Yifu\\Desktop\\test.json"
Does it have to be hard coded?

2021-04-09 15:13 UTC, zhx828 approved these changes

2021-04-09 15:14 UTC, merged