Fixed issue 3755
oncokb/oncokb pull request #3756
Opened 2024-07-12 20:06 UTC by carrotcatnyc

Fixed #3755 - three letter AA converts to 1 letter AA - not case sensitive as far as I can tell

2024-07-15 18:21 UTC, zhx828 requested changes

2024-07-15 20:18 UTC, carrotcatnyc commented on core/src/main/java/org/mskcc/cbio/oncokb/model/Alteration.java
> +        this.alteration = AminoAcidConverterUtils.resolveHgvspShortFromHgvsp(alteration);;
Fixed

2024-07-17 18:06 UTC, calvinlu3 commented on core/src/main/java/org/mskcc/cbio/oncokb/model/Alteration.java
> +        this.alteration = AminoAcidConverterUtils.resolveHgvspShortFromHgvsp(alteration);;
@zhx828 I feel like we should still save the original alteration in the Query object for the end user to have a data point to match response. Maybe we add an hgvsp short field to query?

2024-07-17 18:58 UTC, zhx828 commented on core/src/main/java/org/mskcc/cbio/oncokb/model/Query.java
> +        this.alteration = AminoAcidConverterUtils.resolveHgvspShortFromHgvsp(alteration);;
Add some tests in IndicatorUtilsTest to verify three letters variants are supported.

2024-07-17 18:59 UTC, zhx828 commented on core/src/main/java/org/mskcc/cbio/oncokb/util/AminoAcidConverterUtils.java
> +public class AminoAcidConverterUtils {
Add  AminoAcidConverterUtilsTest under the test folder and test all methods under.

2024-07-18 20:21 UTC, merged